name: weather
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  weather_icons: 3.0.0-nullsafety.0
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^19.3.53
  flutter_screenutil: ^5.0.0+2
  flutter_dotenv: ^5.0.2
  http: ^0.13.3
  freezed_annotation: ^0.14.2
  json_annotation: ^4.0.1
  location: ^4.2.0
  geolocator: ^4.0.3
  bloc_concurrency: ^0.2.0
  flutter_bloc: ^8.0.0
  equatable: ^2.0.3
  loader_overlay: ^2.0.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
  freezed: ^0.14.2
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

